server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-service
          uri: lb://service-service
          predicates:
            - Path=/api/services/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8099/eureka/